### ISSUE TITLE
run unit test in GitHub Actions.

### ISSUE THREAD

**Issue by r-plus** [XVimProject/XVim2#375]
# Roadmap
- [x] ~create self signed cert by CLI~ trying unsign instead of re-sign.
- [x] codesign
- [x] add loadable plugin field to defaults
- [x] automatically run unit test
- [x] got unit test result then print
- [x] exit 1 if not passed

working tree: https://github.com/r-plus/XVim2/tree/ci/unit_test

**Comment by r-plus** [comment]
did it!

Success log: https://github.com/r-plus/XVim2/runs/2396833192?check_suite_focus=true
Failed log: https://github.com/r-plus/XVim2/runs/2396812967?check_suite_focus=true
